create table calendar_units
(
    id          int generated by default as identity,
    day         smallint,
    month       smallint,
    notify      boolean,
    source_id   varchar(36) not null,
    source_type varchar(64) not null,
    year        smallint,
    primary key (id)
);
GO