version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/relic"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/persistence"
    schedule:
      interval: "daily"
