version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
    labels:
      - "dependencies"
    reviewers:
      - "ramizdemiurge"
