relic:
  port: 9091
  database:
    path: "./temp/demo_database.h2"
  authorization:
    password: "toor"
    outside-access: true

spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false
