server:
  port: 9090

spring:

  security:
    user:
      password: toor

  datasource:
    url: jdbc:h2:file:./databases/demo_database.h2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false
