create table calendar_units
(
    uuid        bigint generated by default as identity,
    day         smallint,
    month       smallint,
    source_id   varchar(36)  not null,
    source_type varchar(64) not null,
    year        smallint,
    primary key (uuid)
)
GO
